package com.iora.erp.enumeration;

public enum AccessRights {
    SYSADMIN_EMP, SYSADMIN_JOBTITLE, SYSADMIN_DEPT, SYSADMIN_SITE, SYSADMIN_COMPANY, SYSADMIN_VENDOR,
    PRODUCT_MGMT, MARKETING, ONLINE_ORDER, CUSTOMER_RS, REPORT_ANALYST, INVENTORY_MGMT,
    WAREHOUSE_INV, WAREHOUSE_ORDER, STORE_INV, STORE_PICK, STORE_ORDER, STORE_ORDER_M,
    CUSTOMER_SELFORDER, CUSTOMER_ONLINE   
}
